apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  ports:
    - name: default
      port: {{ .Values.port }}
      protocol: TCP
    {{- with .Values.extraExposePorts }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  selector:
    {{- include "faklody.labels" . | nindent 4 }}
    release: {{ .Release.Name }}
